### ISSUE TITLE
Incorrect SVN export

### ISSUE THREAD

**Issue by JonathonReinhart** [google/ipaddr-py#114]
The tool or person who exported this from SVN to Git did not know what they were doing. Passing `-s` tells `git-svn` that the SVN repo used a "standard" layout (trunk/, tags/, branches/) and creates the Git equivalents.

Can someone *please* re-do this the right way? I would, but I can't access the original google code webpage.

**Comment by pmoody-** [comment]
highly unlikely. 

code.google.com/p/ipaddr-py redirects to github.com/google/ipaddr-py, so I don't think anyone has access to the original svn repo.

**Comment by JonathonReinhart** [comment]
The original SVN repo is still accessible. I'm actually in the process of correctly making this a Git repo right now.

**Comment by pmoody-** [comment]
OOC, what's actually broken?

**Comment by JonathonReinhart** [comment]
The `/trunk`, `/tags`, `/branches` directories are an SVN-ism and shouldn't really be visible in Git. When I `git clone` this repo, I should have the same working copy that you had when this was developed in SVN.

**Comment by JonathonReinhart** [comment]
Have a look at https://github.com/JonathonReinhart/ipaddr-py. It's not perfect, because there are a lot of strange gaps that occur when you "merge" in SVN without actually merging, or push to tags.

**Comment by JonathonReinhart** [comment]
Also, I see that `ipaddr` is at 2.1.11 on [pypi](https://pypi.python.org/pypi/ipaddr), but there's no 2.1.11 tag in SVN.

**Comment by pmoody-** [comment]
I believe the cutover to git happened long before 2.1.11 was cut. 

As far as re-importing this, I'm disinclined to spend any time on it but maybe Mike or someone else who's still at google might be willing.

**Comment by JonathonReinhart** [comment]
I spent some time on it, but it didn't come out perfect. There are lots of
gaps, and I'm not sure why. It might need some real surgery. I just hate to
see history get trashed.

**Comment by shields** [comment]
Ok, I've tried to fix this using a reimport, and generally cleaned up a bit.  It's not great, but maybe we can keep things clean going forward.

**Comment by JonathonReinhart** [comment]
Thanks, this looks a lot better. There is still a "wiki" directory in the top-level directory on "master", but that can probably be cleaned up, like you said.
