### ISSUE TITLE
plans for Python 3.x support?

### ISSUE THREAD

**Issue by slieberth** [google/ipaddr-py#117]
Michael, all

thanks for providing ipaddr, I used it on 2.7 and it works like a charm ... 

Do you have plans to migrate to python 3.x? I guess there is significant work to be done due to the change of types in 3.x (default for int in 3.x)

pls let me know, if I can support ...

BR Stefan

**Comment by shields** [comment]
On Mon, Dec 21, 2015 at 9:15 AM, Stefan Lieberth <notifications@github.com>
wrote:

> Do you have plans to migrate to python 3x?


ipaddr is the basis for the ipaddress module that is part of the standard
library since 3.3.

**Comment by slieberth** [comment]
Hi Michael,

thanks for clarification,  I see ipaddress is the way to move forward… 

greetings from Berlin 
Stefan
