### ISSUE TITLE
"ip_int=0L" variable have a extra string in ipaddr.py

### ISSUE THREAD

**Issue by ushell** [google/ipaddr-py#120]
in ipaddr.py file 1480 lines:
```python
# Now, parse the hextets into a 128-bit integer.
  ip_int = 0L
```
the variable "ip_int=0L" is wrong when python setup.py build,
the right variable is "ip_int = 0" ?

**Comment by mbward** [comment]
Looks like this module doesn't support Python 3.  There's a few other ways it would break too.  I'll send a patch.

**Comment by mbward** [comment]
Wait, ghost already sent https://github.com/google/ipaddr-py/pull/118.  I'll ping the maintainers...
