### ISSUE TITLE
pypi broken

### ISSUE THREAD

**Issue by projekt01** [google/ipaddr-py#121]
The release on pypi is broken for at least 2.1.7. There is a 2.1.10 package in the relase list for ipaddr 2.1.7:

https://pypi.python.org/pypi/ipaddr/2.1.7

Can you upload the correct release. Or probably enable the hidden upload in the pypi admin backend?
Regards Roger Ineichen

**Comment by hugovk** [comment]
https://pypi.python.org/pypi/ipaddr now shows only 2.2.0.

@projekt01 Can this be closed?

**Comment by projekt01** [comment]
@hugovk, yes, the newest release get listed by default, it looks good to me

**Comment by hugovk** [comment]
@projekt01 Please can you click the button to close this issue?

**Comment by projekt01** [comment]
The wrong release file ipaddr-2.1.10.tar.gz is still listed in the 2.1.7 release files list. And the 2.1.10 doesn't contain any release file.
See: https://pypi.org/project/ipaddr/2.1.7/#files
It should not be possible to install the 2.1.7 release this way. Since the 2.2.0 release seems ok, I close the issue but it's not fixed.
