### ISSUE TITLE
pypi does not have working python 3 version

### ISSUE THREAD

**Issue by jsharris** [google/ipaddr-py#122]
Code appears to have been updated for python3 but pypi still has an ancient version.
Please upload the latest version.

**Comment by altendky** [comment]
I think it just doesn't work at all in any Python because of the `0L` that was fixed at the same time as the Python 3 compatibility.

2566dcdc52eda547f90b00fd42c4432407a6ddfe

**Comment by Wenzel** [comment]
Can anyone upload an updatedn python3 compatible version of `ipaddr` on Pypi ?
Is there anything blocking you ?

**Comment by mbward** [comment]
I believe @shields is the only one with access.

@shields if that's correct, could you add me as a maintainer too please?  I'm mikelward on Pypi.

**Comment by mbward** [comment]
I just got permissions and did a release.  Not sure if I did it right, please let me know if you see any problems.
